services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:8.2
    container_name: redis
    ports:
      - "6379:6379"
